config/routes.rb
Nomster::Application.routes.draw do
  get "photos/create"
  devise_for :users

  root 'places#index'

  resources :places do
    resources :comments, :only => :create
    resources :photos, :only => :create
  end

  resources :users, :only => :show 

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :place
  # after_create :send_comment_email

  RATINGS = {
    'one star' => '1_star',
    'two stars' => '2_stars',
    'three stars' => '3_stars',
    'four stars' => '4_stars',
    'five stars' => '5_stars'
  }

  def humanized_rating
    RATINGS.invert[self.rating]
  end

  # def send_comment_email
  #   NotificationMailer.comment_added(self).deliver
  # end

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
  belongs_to :user
  belongs_to :place
end

app/models/place.rb
class Place < ActiveRecord::Base
  belongs_to :user
  geocoded_by :address
  after_validation :geocode
  validates :name, :presence => true, :length => { :minimum => 2 }
  validates :description, :presence => true
  validates :address, :presence => true
  has_many :comments
  has_many :photos
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :places
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  def create
    @place = Place.find(params[:place_id])
    @place.comments.create(comment_params.merge(:user => current_user))
    redirect_to place_path(@place)
  end

  private

  def comment_params
    params.require(:comment).permit(:message, :rating)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!
  def create
    @place = Place.find(params[:place_id])
    @place.photos.create(photo_params.merge(:user => current_user))
    redirect_to place_path(@place)
  end

  private

  def photo_params
    params.require(:photo).permit(:caption, :picture)
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController

  # Add a filter to authenticate user before any of these actions in the array
  before_action :authenticate_user!, :only => [:create, :new, :edit, :update, :destroy]

  def index
    @places = Place.order(:name).page(params[:page]).per(9)
  end

  def new
    @place = Place.new
  end

  def create
    @place = current_user.places.create(place_params)
    
    if @place.valid? 
      redirect_to place_path(@place)
    else
      render :new, :status => :unprocessable_entity
    end
  end

  def show
    @place = Place.find(params[:id])
    @comment = Comment.new
    @photo = Photo.new
  end

  def edit
    @place = Place.find(params[:id])

    # Check to see if user logged in is user that created the place
    if @place.user != current_user 
      return render :text => 'Sorry, you are not allowed to edit places that you did not create.', :status => 'forbidden'
    end
  end

  def update
    @place = Place.find(params[:id])

    # Check to see if user logged in is user that created the place
    if @place.user != current_user
      return render :text => 'Sorry, you are not allowed to edit places that you did not create.', :status => 'forbidden'
    end

    @place.update_attributes(place_params)
    redirect_to root_path
  end

  def destroy
    @place = Place.find(params[:id])

    # Check to see if user logged in is user that created the place
    if @place.user != current_user 
      return render :text => 'Sorry, you are not allowed to edit places that you did not create.', :status => 'forbidden'
    end

    @place.destroy
    redirect_to root_path
  end

  private

  def place_params
    params.require(:place).permit(:name, :address, :description)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nomster John Ellison</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
</head>
<body>
  <nav class="navbar" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <%= link_to 'Nomster', root_path, :class => 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to new_place_path do %>
            <i class="glyphicon glyphicon-plus-sign"></i>
            Add New Place
          <% end %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to 'My Profile', user_path(current_user) %></li>
          <li><%= link_to 'Log Out', destroy_user_session_path, :method => :delete %></li>
        <% else %>
          <li><%= link_to 'Log In', new_user_session_path %></li>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<!-- Alerts & Notifications Generated by Devise -->
<% if notice.present? %>
  <p class="alert alert-info"><%= notice %></p>
<% end %>
<% if alert.present? %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>


<%= yield %>

</body>
</html>

app/views/photos/create.html.erb
<h1>Photos#create</h1>
<p>Find me in app/views/photos/create.html.erb</p>

app/views/places/edit.html.erb
<div class="m-place-box col-xs-10 col-xs-offset-1">
  <h1>Edit The Details of <em><%= @place.name %></em></h1>
  <%= simple_form_for @place do |f| %>
    <%= f.error_notification %>
    <%= f.input :name, placeholder: 'San Festivollo' %>
    <%= f.input :address, placeholder: '123 Street Way...' %>
    <%= f.input :description, placeholder: 'An eclectic restaurant with...' %>
    <%= f.submit 'Update', :class => 'btn btn-primary' %>
    <% end %>
</div>

app/views/places/index.html.erb
<div id="masonry-container" class="transitions-enabled infinite-scroll clearfix">
  <% @places.each do |place| %>
      <div class="m-place-wrapper">
        <%= link_to place_path(place) do %>
          <% if place.photos.present? %>
            <%= image_tag place.photos.last.picture, :width => "236", :class => "m-place-picture" %>
          <% end %>
          <h3 class="m-place-name"><%= place.name %></h3>
        <% end %>
        <div class="m-place-details">
          <p class="m-place-address"><%= place.address %></p>
        </div>
        <% if place.user.present? %>
          <div class="m-place-details">
            <%= image_tag 'user.svg', :class => 'm-place-user-pic' %>
            <p class="m-place-user"><%= place.user.email %></p>
            <div class="clearfix"></div>
          </div>
        <% end %>
      </div>
   
  <% end %>
</div>

<%= paginate @places, :outer_window => 3 %>

<script>
    $(function() {
      var $container = $('#masonry-container');
      $container.imagesLoaded(function() {
        $container.masonry({
          itemSelector: '.m-place-wrapper',
          gutterWidth: 15,
          columnWidth: 236,
          isFitWidth: true,
          isAnimated: !Modernizr.csstransitions
        });
      });

      $container.infinitescroll({
        navSelector: 'nav.pagination',
        nextSelector: 'nav.pagination a[rel=next]',
        itemSelector: '#masonry-container .m-place-wrapper',
        loading: {
          finishedMsg: 'No more places to load. Add a new one!',
          img: '/assets/masonry/loader.gif',
          msgText: 'Loading more places...'
        }
      },
      function( newElements ) {
        var $newElems = $( newElements ).css({ opacity: 0 });
        $newElems.imagesLoaded(function() {
          $newElems.animate({ opacity: 1 })
          $container.masonry('appended', $newElems, true);
        });
      });
    });
</script>

app/views/places/new.html.erb
<div class="m-place-box col-xs-10 col-xs-offset-1">
  <h1>Enter The Details of Your Place</h1>
  <%= simple_form_for @place do |f| %>
    <%= f.error_notification %>
    <%= f.input :name, placeholder: 'San Festivollo' %>
    <%= f.input :address, placeholder: '123 Street Way...' %>
    <%= f.input :description, placeholder: 'An eclectic restaurant with...' %>
    <%= f.submit 'Create', :class => 'btn btn-primary' %>
    <% end %>
</div>

app/views/places/show.html.erb
<!-- Place Description & Map -->
<div class="container-fluid">
  <div class="row">
    <div class="m-place-box col-xs-10 col-xs-offset-1">
      <hgroup class="m-place-heading">
        <h1><%= @place.name %></h1>
        <h3 class="subheader"><%= @place.address %></h3>
      </hgroup>
      <p class="lead"><%= @place.description %></p>
    
      <!-- Load map if geocoder coordinates are present -->
      <% if @place.latitude.present? && @place.longitude.present? %>
      <!-- Render Google Map -->
      <div id="map-canvas">
        
      </div>
      <!-- Google Maps API JS -->
      <script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>
      <script>
      function initialize() {
        var myLatlng = new google.maps.LatLng(<%= @place.latitude %>, <%= @place.longitude %>);
        var mapOptions = {
          zoom: 14,
          center: myLatlng
        }
        var map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);
    
        var marker = new google.maps.Marker({
            position: myLatlng,
            map: map,
            title: 'Hello World!'
        });
      }
    
      google.maps.event.addDomListener(window, 'load', initialize);
    
      </script>
      <% end %>
    
      <div class="pull-right m-place-edit-container">
        <% if current_user && current_user == @place.user %>
          <%= link_to 'Edit', edit_place_path(@place), :class => 'btn btn-primary' %>
          <%= link_to 'Delete', place_path(@place), :method => :delete, :data => {:confirm => 'Are you sure you want to delete this place?'}, :class => 'btn btn-danger' %>
        <% end %>
      </div>
    
    </div>
  </div>
</div>


<!-- photo block -->
<div class="container-fluid">
  <div class="row">
    <div class="m-place-box col-xs-10 col-xs-offset-1">
      <% if @place.photos.present? %>
        <h2 class="m-photo-heading">Photos of <%= @place.name %></h2>
        <div class="row">
        <% @place.photos.each do |photo| %>
          <div class="col-md-6 col-lg-4 m-photo-container">
            <%= image_tag photo.picture, :class => 'm-photo-picture' %>
            <div class="clear"></div>
            <p class="m-photo-caption">
              <%= photo.caption %>
            </p>
          </div>
        <% end %>
        </div>

      <% else %>
        <h2>Add a Photo</h2>
      <% end %>

    
      <!-- Button trigger add photo modal -->
      <button class="btn btn-primary btn-lg pull-right m-photo-button" data-toggle="modal" data-target="#addPhotoModal">
        Add Photo
      </button>
    
      <!-- Add Photo Modal -->
      <div class="modal fade" id="addPhotoModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
              <h4 class="modal-title" id="myModalLabel">Add Photo of <%= @place.name %></h4>
            </div>
            <div class="modal-body">
              <%= simple_form_for @photo, :url => place_photos_path(@place) do |f| %>
                <%= f.input :picture %>
                <%= f.input :caption %>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <%= f.submit 'Upload', :class => 'btn btn-primary' %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    
    </div>
  </div>
</div>

<!-- comment block -->
<div class="m-place-box col-xs-10 col-xs-offset-1">
  <% if @place.comments.present? %>
    <h2 class="m-comments-heading">Comments for <%= @place.name %></h2>
    <% @place.comments.each do |comment| %>
      <div class="col-md-6">
        <blockquote>
          <p><strong></strong> <%= comment.message %></p>
          <br>
          <% if comment.humanized_rating.present? %>
            <b><strong></strong> <%= comment.humanized_rating %></b>
          <% end %>
          <small><%= comment.user.email %></small>
        </blockquote>
      </div>
    <% end %>
  <% else %>
    <h2>Add a Comment</h2>
  <% end %>

  <!-- Button trigger modal -->
  <button class="btn btn-primary btn-lg pull-right" data-toggle="modal" data-target="#myModal">
    Comment
  </button>

  <!-- Modal -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title" id="myModalLabel">Comment on <%= @place.name %></h4>
        </div>
        <div class="modal-body">
          <%= simple_form_for @comment, :url => place_comments_path(@place) do |f| %>
            <%= f.input :message %>
            <%= f.input :rating, :as => :select, :collection => Comment::RATINGS %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <%= f.submit 'Comment', :class => 'btn btn-primary' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="m-place-box col-xs-10 col-xs-offset-1">
      <div class="col-sm-1">
        <%= image_tag 'user.svg', :class => 'm-profile-pic' %>
      </div>
      <div class="col-sm-11">
        <hgroup>
          <h1>Welcome! <%= @user.email %></h1>
          <h3>Member since: <%= @user.created_at.strftime("%B %d, %Y") %></h3>
          <h4><%= @user.comments.count %> total comments</h4>
          <h5><%= @user.comments.where(:rating => '5_stars').count %> total 5 star reviews</h5>
        </hgroup>
      </div>
      <div class="clear"></div>
    </div>
  </div>
</div>

<!-- comments -->
<div class="container-fluid">
  <div class="row">
    <div class="m-place-box col-xs-10 col-xs-offset-1">
      <h2 class="m-comment-heading">My Comments</h2>
      <% @user.comments.each do |comment| %>
        <div class="col-xs-12 col-sm-6">
          <h3 class="m-comment-heading"><%= link_to comment.place.name, place_path(comment.place) %></h3>
           <blockquote>
             <% if comment.humanized_rating.present? %>
               <b><%= comment.humanized_rating %></b> -
             <% end %>
             <%= comment.message %>
             <small><%= comment.user.email %></small>
           </blockquote>
         </div>
         <div class="clear"></div>
      <% end %>
    </div>
  </div>
</div>

<!-- places -->
<div class="container-fluid">
  <div class="row">
    <div class="m-place-box col-xs-10 col-xs-offset-1">
      <h2 class="m-place-heading">My Places</h2>
      <% @user.places.each do |place| %> 
  <div class="m-place-box col-xs-10 col-xs-offset-1">
    <h1><%= link_to place.name, place_path(place) %></h1>
    <h2 class="subheader"><i><%= place.address %></i></h2>
    <p><%= place.description %></p>
    <% if place.photos.present? %>
      <%= image_tag place.photos.last.picture, :size => "250x250" %>
    <% end %>
  </div>
<% end %>
    </div>
  </div>
</div>